config/routes.rb
Rails.application.routes.draw do
  root    'posts#index'

  get     '/signup',  to: 'users#new'
  get     '/login',   to: 'sessions#new'
  post    '/login',   to: 'sessions#create'
  delete  '/logout',  to: 'sessions#destroy'
  
  resources :users, except: :index do
    resources :posts
  end

  resources :posts do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates_presence_of :post_id, :user_id
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  default_scope -> { order(created_at: :desc) }
  validates_presence_of :content, :title, :user_id
  validates :title, presence: true,
                    length: { minimum: 5 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  attr_accessor :remember_token
  before_save { email.downcase! }
  validates_presence_of :username, :email, :password
  validates :username, length: { maximum: 15 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }, allow_nil: true

  class << self
    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                    BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :correct_user,  only: [:new, :create]
  before_action :set_post,      only: [:new, :create]

  def new
    @comment = Comment.new
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    if @comment.save
      flash[:success] = "Comment was successfully created."
      redirect_to user_post_path(@user, @post)
    else
      flash[:alert] = "Something went wrong."
    end
  end
 
  private

  def comment_params
    params.require(:comment).permit(:content)
  end

  def correct_user
    @user = current_user
    redirect_to(root_url) unless current_user?(@user)
  end

  def set_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post,      only: [:show, :edit, :update, :destroy]
  before_action :set_user,      only: [:create, :show, :edit, :update, :destroy]
  before_action :correct_user,  only: [:edit, :update, :destroy]

  def index
    @posts = Post.all
  end

  def show
    @post = set_post
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = @user.posts.new(post_params)

    if @post.save
      flash[:success] = "Post was successfully created."
      redirect_to user_post_path(@user, @post)
    else
      render :new
    end
  end

  def update
    if @post.update(post_params)
      flash[:success] = "Post was successfully updated."
      redirect_to user_post_path(@post.user, @post)
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    flash[:success] = "Post was successfully destroyed."
    redirect_to user_posts_path
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def set_user
    @user = User.find(params[:user_id])
  end

  def post_params
    params.require(:post).permit(:title, :content)
  end

  def correct_user
    @user = User.find(params[:user_id])
    redirect_to(root_url) unless current_user?(@user)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user && @user.authenticate(params[:session][:password])
      log_in @user
      flash[:success] = "You are now logged in."
      params[:session][:remember_me] == "1" ? remember(@user) : forget(@user)
      redirect_back_or @user
    else
      flash.now[:alert] = "Invalid email/password combination."
      render "new"
    end
  end

  def destroy
    log_out if logged_in?
    flash[:success] = "You are now logged out."
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:show, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update, :destroy]
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      remember @user
      flash[:success] = "Welcome, #{@user.username}!"
      redirect_to @user
    else
      render :new
    end
  end

  def update
    if @user.update(user_params)
      redirect_to @user
      flash[:success] = "#{@user.username} was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to root_path
    flash[:success] = "#{@user.username} was successfully destroyed."
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

  def logged_in_user
    unless logged_in?
      store_location
      flash[:alert] = "Please log in."
      redirect_to login_url
    end
  end

  def correct_user
    @user = User.find(params[:id]) || User.find(params[:user_id])
    redirect_to(root_url) unless current_user?(@user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def format_date(date = DateTime.new)
    date.strftime("%b %d, %Y")
  end

  def full_title(page_title = "")
    base_title = "reddit"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/flashes_helper.rb
module FlashesHelper
  def user_facing_flashes
    flash.to_hash.slice("alert", "error", "notice", "success")
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def current_user?(user)
    user == current_user
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "gravatar")
  end
end

app/views/application/_analytics.html.erb
<% if ENV["SEGMENT_KEY"] %>
  <script type="text/javascript">
    window.analytics=window.analytics||[],window.analytics.methods=["identify","group","track","page","pageview","alias","ready","on","once","off","trackLink","trackForm","trackClick","trackSubmit"],window.analytics.factory=function(t){return function(){var a=Array.prototype.slice.call(arguments);return a.unshift(t),window.analytics.push(a),window.analytics}};for(var i=0;i<window.analytics.methods.length;i++){var key=window.analytics.methods[i];window.analytics[key]=window.analytics.factory(key)}window.analytics.load=function(t){if(!document.getElementById("analytics-js")){var a=document.createElement("script");a.type="text/javascript",a.id="analytics-js",a.async=!0,a.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.com/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(a,n)}},window.analytics.SNIPPET_VERSION="2.0.9",
    window.analytics.load("<%= ENV["SEGMENT_KEY"] %>");
    window.analytics.page();
  </script>
<% end %>

app/views/application/_css_overrides.html.erb
<% if Rails.env.test? %>
  <style type="text/css">
    * {
      transition-property: none !important;
    }
  </style>
<% end %>

app/views/application/_flashes.html.erb
<% if flash.any? %>
  <div class="flashes">
    <% user_facing_flashes.each do |key, value| -%>
      <div class="flash-<%= key %>">
        <%= value %>
      </div>
    <% end -%>
  </div>
<% end %>

app/views/application/_javascript.html.erb
<%= javascript_include_tag :application %>

<%= yield :javascript %>

<%= render "analytics" %>

<% if Rails.env.test? %>
  <%= javascript_tag do %>
    $.fx.off = true;
    $.ajaxSetup({ async: false });
  <% end %>
<% end %>

app/views/comments/new.html.erb
<article class="form-container">
  <h3 class="show-title">Add a comment:</h3>
  <%= form_for([@post, @comment]) do |f| %>
    <div class="field">
      <%= f.text_area :content, class: "input text-area-input" %>
    </div>
    <div class="action">
      <%= f.submit class: "button" %>
    </div>
  <% end %>
</article>

app/views/layouts/_footer.html.erb
<footer class="site-footer">
  <p class="byline">Reddit Clone © <%= link_to "Bison Hubert", "http://bisonhubert.com", target: "_blank", rel: "noopener", class: "site-link portfolio-link" %> 2017</p>
</footer>

app/views/layouts/_header.html.erb
<header class="site-header">
  <article class="title-card">
    <%= link_to image_tag("reddit-logo-head-small.png", alt: "reddit-logo", class: "logo"), root_path %>
    <h1 class="site-name"><%= link_to "Reddit", root_path, class: "root-link" %></h1>
  </article>
  <nav class="site-nav center-nav">
    <%= link_to "Home", root_url, class: "site-link" %>
    <% if logged_in? %>
      <%= link_to "New Post", new_user_post_path(current_user), class: "site-link" %>
      <%= link_to "Profile", current_user, class: "site-link" %>
      <%= link_to "Log out", logout_path, method: :delete, class: "site-link" %>
    <% else %>
      <%= link_to "Log in", login_path, class: "site-link" %>
    <% end %>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="ROBOTS" content="NOODP" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag :application, media: "all" %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= body_class %>">
  <%= render "layouts/header" %>
  <%= render "flashes" -%>
  <main class="main-content">
    <%= yield %>
  </main>
  <%= render "javascript" %>
  <%= render "css_overrides" %>
  <%= render "layouts/footer" %>
  <%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/posts/edit.html.erb
<% provide(:title, "Edit Post") %>
<% provide(:button_text, "Edit") %>

<article class="form-container">
  <h2 class="form-title"><%= yield(:title) %></h2>

  <%= form_for([@post.user, @post], url: user_post_path(@post.user, @post)) do |f| %>
    <% if @post.errors.any? %>
      <div id="error-explanation">
        <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

        <ul>
        <% @post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :title, class: "label" %>
      <%= f.text_field :title, class: "input" %>
    </div>

    <div class="field">
      <%= f.label :content, class: "label" %>
      <%= f.text_area :content, class: "input text-area-input" %>
    </div>

    <div class="actions">
      <%= f.submit yield(:button_text), class: "button" %>
    </div>
  <% end %>
</article>

<nav class="site-nav content-nav">
  <%= link_to "Back to article", user_post_path(@post.user_id, @post), class: "site-link content-link" %>
</nav>

app/views/posts/index.html.erb
<%= provide(:title, "Home") %>

<ol class="posts">
  <% @posts.each do |post| %>
    <li class="post-index">
      <h2 class="post-title"><%= link_to post.title, user_post_path(post.user, post), class: "post-link" %>
      </h2>
      <span class="post-byline">by <%= link_to post.user.username, user_path(post.user), class: "post-author" %>
      </span>
    </li>
  <% end %>
</ol>

app/views/posts/new.html.erb
<% provide(:title, "Add a post") %>
<% provide(:button_text, "Create post") %>

<article class="form-container">
  <h2 class="form-title"><%= yield(:title) %></h2>

  <%= form_for([@user, @post], url: user_posts_path) do |f| %>
    <% if @post.errors.any? %>
      <div id="error-explanation">
        <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

        <ul>
        <% @post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :title, class: "label" %>
      <%= f.text_field :title, class: "input" %>
    </div>

    <div class="field">
      <%= f.label :content, class: "label" %>
      <%= f.text_area :content, class: "input text-area-input" %>
    </div>

    <div class="actions">
      <%= f.submit yield(:button_text), class: "button" %>
    </div>
  <% end %>
</article>
<nav class="site-nav content-nav">
  <%= link_to "Back", user_posts_path, class: "site-link content-link" %>
</nav>

app/views/posts/show.html.erb
<%= provide(:title, @post.title) %>

<article class="show-wrapper">
  <h2 class="show-title">
    <%= @post.title %>
  </h2>
  <p class="show-content">
    <%= @post.content %>
  </p>
  <div class="previous-post-publish-date post-publish-date">Published on <%= format_date(@post.created_at) %>
  </div>
  <div class="post-byline">by <%= link_to @post.user.username, user_path(@post.user), class: "post-author" %>
  </div>
  </p>
</article>
<section class="post-comments">
  <% if @post.comments.any? %>
    <ol class="comments-list">
      <% @post.comments.each do |comment| %>
        <%= comment.content %>
      <% end %>
    </ol>
  <% end %>
  <% if logged_in? %>
    <%= link_to "Add a new comment", new_post_comment_path(@post), class: "site-link content-link" %>
  <% end %>
</section>
<nav class="site-nav content-nav">
  <% if logged_in? && @post.user == current_user %>
  <%= link_to "Edit", edit_user_post_path(@post.user, @post), class: "site-link content-link" %>
  <%= link_to "Destroy", user_post_path(@post.user_id, @post), method: :delete, data: { confirm: "Are you sure?" }, class: "site-link content-link" %>
  <% end %>
  <%= link_to "Back", user_posts_path, class: "site-link content-link" %>
</nav>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error-explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username, class: "label" %>
    <%= f.text_field :username, class: "input" %>
  </div>

  <div class="field">
    <%= f.label :email, class: "label" %>
    <%= f.text_field :email, class: "input" %>
  </div>

  <div class="field">
    <%= f.label :password, class: "label" %>
    <%= f.password_field :password, class: "input" %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation, "Confirm password", class: "label" %>
    <%= f.password_field :password_confirmation, class: "input" %>
  </div>

  <div class="actions">
    <%= f.submit yield(:button_text), class: "button" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, @user.username) %>
<% provide(:button_text, "Save changes") %>

<article class="form-container">
  <h2 class="form-title">Update your profile</h2>
  <%= render "form", user: @user %>
  <div class="gravatar-edit">
    <%= gravatar_for @user, class: "gravatar-image" %>
    <a href="http://gravatar.com/emails" rel="noopener" target="_blank" class="gravatar-link site-link content-link">Update Gravatar Image</a>
  </div>
</article>
<nav class="site-nav content-nav">
  <%= link_to "Show", @user, class: "site-link content-link" %>
  <%= link_to "Back", root_path, class: "site-link content-link" %>
  <%= link_to "Close Account", @user, 
                               class: "site-link content-link",
                               method: :delete, 
                               data: { confirm: "Are you sure?" } %>
</nav>

app/views/users/new.html.erb
<% provide(:title, "Sign Up") %>
<% provide(:button_text, "Create my account") %>

<article class="form-container">
  <h2 class="form-title"><%= yield(:title) %></h2>

  <%= render "form", user: @user %>
</article>
<nav class="site-nav content-nav">
  <%= link_to "Back", root_path, class: "site-link content-link" %>
</nav>

app/views/users/show.html.erb
<% provide(:title, @user.username) %>

<article class="show-wrapper">
  <div class="show-content profile-content">
    <%= gravatar_for @user, class: "gravatar-image" %>
    <h2 class="show-title profile-name">
      <%= @user.username + "'s Profile" %>
    </h2>
  </div>
</article>
<section class="previous-posts-wrapper post-wrapper">
  <h3 class="previous-posts-title posts-title">Older Posts</h3>
  <% @user.posts.each do |post| %>
    <article class="previous-post post">
      <h2 class="previous-post-title post-title"><%= link_to post.title, user_post_path(post.user, post), class: "previous-post-link post-link" %>
      </h2>
      <span class="previous-post-publish-date post-publish-date">Published on <%= format_date(post.created_at) %>
      </span>
    </article>
  <% end %>
</section>
<nav class="site-nav content-nav">
  <%= link_to "Settings", edit_user_path(current_user), class: "site-link content-link"  %>
  <%= link_to "Back", root_path, class: "site-link content-link"  %>
</nav>